// Code generated by gen_commands.go; DO NOT EDIT.
package api

/*
This file is auto-generated from YAML command schemas.
*/

// ConfirmInitialization: Confirm initialization of a daemon and provide configuration
type ConfirmInitialization struct {
    Init map[string]interface{} `yaml:"init" json:"init"` // the configuration of the daemon, property_name and index indexed
    Port map[string]interface{} `yaml:"port" json:"port"` // the configuration of the instrument ports
    Timestamp string `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// Get: Execute a get instruction on a sandboxed instrument
type Get struct {
    Property string `yaml:"property" json:"property"` // The name of the property that is to be set
    Index int `yaml:"index" json:"index"` // The particular index of a instrument that is to be set
}

// Log: Contains the necessary substrings for a logging style command
type Log struct {
    Message string `yaml:"message" json:"message"` // The contents of the log message
    Timestamp string `yaml:"timestamp" json:"timestamp"` // When the response was completed
    Hash string `yaml:"hash" json:"hash"` // the hash for the requesting unit
}

// PerformArbitraryMethod: Enact an arbitrary submethod for a given instrument daemon from the CLI
type PerformArbitraryMethod struct {
    Method string `yaml:"method" json:"method"` // The name of the method that is to be performed
    KeywordArgs map[string]interface{} `yaml:"keyword_args" json:"keyword_args"` // Arbitrary keyword arguments to be passes to the method
    Timestamp string `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// ReturnData: Returns measured data
type ReturnData struct {
    Data []interface{} `yaml:"data" json:"data"` // The measured data collected on the instrument
}

// ReturnGet: Response from a get instruction on a sandboxed instrument
type ReturnGet struct {
    Value interface{} `yaml:"value" json:"value"` // The argument to be set inside the instrument
    Timestamp string `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// Set: Execute a set instruction on a sandboxed instrument
type Set struct {
    Property string `yaml:"property" json:"property"` // The name of the property that is to be set
    Index int `yaml:"index" json:"index"` // The particular index of a instrument that is to be set
    Value interface{} `yaml:"value" json:"value"` // The argument to be set inside the instrument
}

// Status: Provide the status of the process
type Status struct {
    Status interface{} `yaml:"status" json:"status"` // At compilation of this message the state of the process
    Timestamp string `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// Trigger: Execute a trigger/arm on a buffered instrument
type Trigger struct {
    Property string `yaml:"property" json:"property"` // The name of the property that is to be set
    Index int `yaml:"index" json:"index"` // The particular index of a instrument that is to be set
}

// CommandRegistry maps command names to empty struct instances
var CommandRegistry = map[string]interface{}{
    "CONFIRM_INITIALIZATION": ConfirmInitialization{},
    "GET": Get{},
    "LOG": Log{},
    "PERFORM_ARBITRARY_METHOD": PerformArbitraryMethod{},
    "RETURN_DATA": ReturnData{},
    "RETURN_GET": ReturnGet{},
    "SET": Set{},
    "STATUS": Status{},
    "TRIGGER": Trigger{},
}
