// Code generated by gen_commands.go; DO NOT EDIT.
package api

/*
This file is auto-generated from YAML command schemas.
*/

// Log: Contains the necessary substrings for a logging style command
type Log struct {
	Message   string `yaml:"message" json:"message"`     // The contents of the log message
	Timestamp string `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// MeasurementReady: Indicates that a meassurement is ready for the server to perform
type MeasurementReady struct {
	Getters   []interface{} `yaml:"getters" json:"getters"`       // the connections that are ready to be measured
	Setters   []interface{} `yaml:"setters" json:"setters"`       // the connections that are to be set when buffered
	ProcessId string        `yaml:"process_id" json:"process_id"` // A unique identifier for the process/ measurement and can index it
	Timestamp string        `yaml:"timestamp" json:"timestamp"`   // When the response was completed
}

// ProcessData: Used by interpreter to handle the need to collect some data
type ProcessData struct {
	ProcessId string        `yaml:"process_id" json:"process_id"` // A unique identifier for the process/ measurement and can index it
	Timestamp string        `yaml:"timestamp" json:"timestamp"`   // When the response was completed
	Data      []interface{} `yaml:"data" json:"data"`             // the data taken from the instruments for interpretation
}

// ProcessRequest: A request to the interpreter to process an incoming measurement
type ProcessRequest struct {
	Request        interface{}            `yaml:"request" json:"request"`               // The measurement request from FAlCon
	Configurations map[string]interface{} `yaml:"configurations" json:"configurations"` // The configurations of the instruments loaded into the instrument server
	DataPath       string                 `yaml:"data_path" json:"data_path"`           // The filepath to the spot in the HDF5 database to store the collected data at
	ProcessId      string                 `yaml:"process_id" json:"process_id"`         // A unique identifier for the process/ measurement and can index it
}

// Status: Provide the status of the process
type Status struct {
	Status    interface{} `yaml:"status" json:"status"`       // At compilation of this message the state of the process
	Timestamp string      `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// UpdateDaemonProperty: Issued to selectively update an instruments property in a daemon
type UpdateDaemonProperty struct {
	Property  string      `yaml:"property" json:"property"`   // The main subclass of property
	Name      string      `yaml:"name" json:"name"`           // The human readable name from FAlCon to the wiremap, or at the very least a instrument type if unique
	Value     interface{} `yaml:"value" json:"value"`         // The quantity
	Timestamp string      `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// UploadData: Used by the interpreter to hand data off the the runtime for FAlCon
type UploadData struct {
	Data      interface{} `yaml:"data" json:"data"`           // the jsonable measurement request for the FAlCon to unpack and use
	Timestamp string      `yaml:"timestamp" json:"timestamp"` // When the response was completed
}

// CommandRegistry maps command names to empty struct instances
var CommandRegistry = map[string]interface{}{
	"LOG":                    Log{},
	"MEASUREMENT_READY":      MeasurementReady{},
	"PROCESS_DATA":           ProcessData{},
	"PROCESS_REQUEST":        ProcessRequest{},
	"STATUS":                 Status{},
	"UPDATE_DAEMON_PROPERTY": UpdateDaemonProperty{},
	"UPLOAD_DATA":            UploadData{},
}
