// Code generated by gen_from_schemas.lua — DO NOT EDIT
package measurements

import (
  "encoding/json"
  "fmt"
)

// Domain: Numeric domain with min/max
type Domain struct {
    Max float64 `json:"max"` // Maximum allowed value
    Min float64 `json:"min"` // Minimum allowed value
}

func (rc Domain) ToMap() (map[string]interface{}, error) {
    b, err := json.Marshal(rc)
    if err != nil { return nil, err }
    var m map[string]interface{}
    if err := json.Unmarshal(b, &m); err != nil { return nil, err }
    return m, nil
}

// InstrumentTarget: InstrumentTarget represents a reference to an instrument, optionally with a channel.
type InstrumentTarget struct {
    Channel int `json:"channel"` // Optional channel number
    Id string `json:"id"` // Instrument identifier (e.g., "GPI1")
}

func (rc InstrumentTarget) ToMap() (map[string]interface{}, error) {
    b, err := json.Marshal(rc)
    if err != nil { return nil, err }
    var m map[string]interface{}
    if err := json.Unmarshal(b, &m); err != nil { return nil, err }
    return m, nil
}

// MeasurementResponse: Canonical MeasurementResponse wrapper. Use an annotation x-valueType on instances to indicate the concrete type of `value()`.
type MeasurementResponse struct {
    Instrument string `json:"instrument"` // 
    Type string `json:"type"` // 
    Value interface{} `json:"value"` // The recorded value. Concrete type is indicated in the schema instance via x-valueType (e.g. 'number', 'string', 'boolean', 'buffer').
    Verb string `json:"verb"` // 
}

func (rc MeasurementResponse) ToMap() (map[string]interface{}, error) {
    b, err := json.Marshal(rc)
    if err != nil { return nil, err }
    var m map[string]interface{}
    if err := json.Unmarshal(b, &m); err != nil { return nil, err }
    return m, nil
}

// MeasurementResponseBoolean concrete for MeasurementResponse<boolean>
type MeasurementResponseBoolean struct {
    Instrument string `json:"instrument"`
    Verb string `json:"verb"`
    Type string `json:"type"`
    Value bool `json:"value"`
}

// MeasurementResponseNumber concrete for MeasurementResponse<number>
type MeasurementResponseNumber struct {
    Instrument string `json:"instrument"`
    Verb string `json:"verb"`
    Type string `json:"type"`
    Value float64 `json:"value"`
}

// GetAllVoltagesRequest generated request (inputs) from schema get_all_voltages.json
type GetAllVoltagesRequest struct {
    Getters []InstrumentTarget `json:"getters"` // Instruments to read from.
}

// GetAllVoltagesResponse generated response: slice of MeasurementResponseNumber
type GetAllVoltagesResponse []MeasurementResponseNumber

// GetAllVoltagesSpec pairs request and response types for script get_all_voltages.json
type GetAllVoltagesSpec struct {
    Input GetAllVoltagesRequest `json:"input"`
    Output GetAllVoltagesResponse `json:"output"`
}

// GetManyVoltagesRequest generated request (inputs) from schema get_many_voltages.json
type GetManyVoltagesRequest struct {
    Getters []InstrumentTarget `json:"getters"` // Instruments to read from.
}

// GetManyVoltagesResponse generated response: slice of MeasurementResponseNumber
type GetManyVoltagesResponse []MeasurementResponseNumber

// GetManyVoltagesSpec pairs request and response types for script get_many_voltages.json
type GetManyVoltagesSpec struct {
    Input GetManyVoltagesRequest `json:"input"`
    Output GetManyVoltagesResponse `json:"output"`
}

// GetNumberOfSamplesRequest generated request (inputs) from schema get_number_of_samples.json
type GetNumberOfSamplesRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to collect the number of samples from
}

// GetNumberOfSamplesResponse generated response: single MeasurementResponseNumber
type GetNumberOfSamplesResponse MeasurementResponseNumber

// GetNumberOfSamplesSpec pairs request and response types for script get_number_of_samples.json
type GetNumberOfSamplesSpec struct {
    Input GetNumberOfSamplesRequest `json:"input"`
    Output GetNumberOfSamplesResponse `json:"output"`
}

// GetSampleRateRequest generated request (inputs) from schema get_sample_rate.json
type GetSampleRateRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to collect the number of samples from
}

// GetSampleRateResponse generated response: single MeasurementResponseNumber
type GetSampleRateResponse MeasurementResponseNumber

// GetSampleRateSpec pairs request and response types for script get_sample_rate.json
type GetSampleRateSpec struct {
    Input GetSampleRateRequest `json:"input"`
    Output GetSampleRateResponse `json:"output"`
}

// GetSlopeRequest generated request (inputs) from schema get_slope.json
type GetSlopeRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to collect the slope from. The slope is the DC ramp slope of the gate bias voltage.
}

// GetSlopeResponse generated response: single MeasurementResponseNumber
type GetSlopeResponse MeasurementResponseNumber

// GetSlopeSpec pairs request and response types for script get_slope.json
type GetSlopeSpec struct {
    Input GetSlopeRequest `json:"input"`
    Output GetSlopeResponse `json:"output"`
}

// GetTriggerLeaderRequest generated request (inputs) from schema get_trigger_leader.json
type GetTriggerLeaderRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to check if the leader. The leader is in charge of syncing with the ADC and triggering the rest of the measurements.
}

// GetTriggerLeaderResponse generated response: single MeasurementResponseBoolean
type GetTriggerLeaderResponse MeasurementResponseBoolean

// GetTriggerLeaderSpec pairs request and response types for script get_trigger_leader.json
type GetTriggerLeaderSpec struct {
    Input GetTriggerLeaderRequest `json:"input"`
    Output GetTriggerLeaderResponse `json:"output"`
}

// GetVoltageRequest generated request (inputs) from schema get_voltage.json
type GetVoltageRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to collect the applied voltage from
}

// GetVoltageResponse generated response: single MeasurementResponseNumber
type GetVoltageResponse MeasurementResponseNumber

// GetVoltageSpec pairs request and response types for script get_voltage.json
type GetVoltageSpec struct {
    Input GetVoltageRequest `json:"input"`
    Output GetVoltageResponse `json:"output"`
}

// Measure1DBufferedRequest generated request (inputs) from schema measure_1D_buffered.json
type Measure1DBufferedRequest struct {
    BufferedGetters []InstrumentTarget `json:"bufferedGetters"` // Buffered Instruments to read from. These are the sources from which waveform data will be acquired at each step.
    BufferedSetters []InstrumentTarget `json:"bufferedSetters"` // Buffered Instruments to write to. These are the targets whose voltages or parameters are set for each step in the sweep.
    NumPoints int `json:"numPoints"` // 
    NumSteps int `json:"numSteps"` // Number of steps in the waveform. Determines how many discrete parameter values will be swept.
    SampleRate float64 `json:"sampleRate"` // Sampling rate in Hz. Defines the rate at which waveform data is sampled during acquisition.
    SetVoltageDomains map[string]Domain `json:"setVoltageDomains"` // Voltage ranges per channel. This table maps instrument target identifiers to their allowed or intended voltage sweep domains.
    Setters []InstrumentTarget `json:"setters"` // Instruments to write to. These are the targets whose voltages or parameters are set once during the operation.
}

// Measure1DBufferedResponse generated response: slice of MeasurementResponseNumber
type Measure1DBufferedResponse []MeasurementResponseNumber

// Measure1DBufferedSpec pairs request and response types for script measure_1D_buffered.json
type Measure1DBufferedSpec struct {
    Input Measure1DBufferedRequest `json:"input"`
    Output Measure1DBufferedResponse `json:"output"`
}

// Measure2DBufferedRequest generated request (inputs) from schema measure_2D_buffered.json
type Measure2DBufferedRequest struct {
    BufferedGetters []InstrumentTarget `json:"bufferedGetters"` // Buffered Instruments to read from. These are the sources from which waveform data will be acquired at each step.
    BufferedXSetters []InstrumentTarget `json:"bufferedXSetters"` // Buffered Instruments to write to. These are the targets whose voltages or parameters are set for each step in the x sweep.
    BufferedYSetters []InstrumentTarget `json:"bufferedYSetters"` // Buffered Instruments to write to. These are the targets whose voltages or parameters are set for each step in the y sweep.
    NumPoints int `json:"numPoints"` // 
    NumXSteps int `json:"numXSteps"` // Number of steps in the x axis waveform. Determines how many discrete parameter values will be swept.
    NumYSteps int `json:"numYSteps"` // Number of steps in the y axis waveform. Determines how many discrete parameter values will be swept.
    SampleRate float64 `json:"sampleRate"` // Sampling rate in Hz. Defines the rate at which waveform data is sampled during acquisition.
    SetXVoltageDomains map[string]Domain `json:"setXVoltageDomains"` // X Voltage ranges per channel. This table maps instrument target identifiers to their allowed or intended voltage sweep domains.
    SetYVoltageDomains map[string]Domain `json:"setYVoltageDomains"` // Y Voltage ranges per channel. This table maps instrument target identifiers to their allowed or intended voltage sweep domains.
    Setters []InstrumentTarget `json:"setters"` // Instruments to write to. These are the targets whose voltages or parameters are set once during the operation.
}

// Measure2DBufferedResponse generated response: slice of MeasurementResponseNumber
type Measure2DBufferedResponse []MeasurementResponseNumber

// Measure2DBufferedSpec pairs request and response types for script measure_2D_buffered.json
type Measure2DBufferedSpec struct {
    Input Measure2DBufferedRequest `json:"input"`
    Output Measure2DBufferedResponse `json:"output"`
}

// MeasureCurrentRequest generated request (inputs) from schema measure_current.json
type MeasureCurrentRequest struct {
    Getters []InstrumentTarget `json:"getters"` // Instruments to read from.
    SampleRate float64 `json:"sampleRate"` // Sampling rate in Hz. Defines the rate at which waveform data is sampled during acquisition.
}

// MeasureCurrentResponse generated response: slice of MeasurementResponseNumber
type MeasureCurrentResponse []MeasurementResponseNumber

// MeasureCurrentSpec pairs request and response types for script measure_current.json
type MeasureCurrentSpec struct {
    Input MeasureCurrentRequest `json:"input"`
    Output MeasureCurrentResponse `json:"output"`
}

// MeasureGetSetRequest generated request (inputs) from schema measure_get_set.json
type MeasureGetSetRequest struct {
    Getters []InstrumentTarget `json:"getters"` // Instruments to read from.
    NumPoints int `json:"numPoints"` // 
    SampleRate float64 `json:"sampleRate"` // Sampling rate in Hz. Defines the rate at which waveform data is sampled during acquisition.
    SetVoltages map[string]float64 `json:"setVoltages"` // Table mapping instrument target identifiers (as strings) to voltage values to set in V.
    Setters []InstrumentTarget `json:"setters"` // Instruments to write to.
}

// MeasureGetSetResponse generated response: slice of MeasurementResponseNumber
type MeasureGetSetResponse []MeasurementResponseNumber

// MeasureGetSetSpec pairs request and response types for script measure_get_set.json
type MeasureGetSetSpec struct {
    Input MeasureGetSetRequest `json:"input"`
    Output MeasureGetSetResponse `json:"output"`
}

// MeasureIlluminationRequest generated request (inputs) from schema measure_illumination.json
type MeasureIlluminationRequest struct {
    Getters []InstrumentTarget `json:"getters"` // Instruments to read from.
    IlluminationTime float64 `json:"illuminationTime"` // Time in seconds to illuminate the device.
    SampleRate float64 `json:"sampleRate"` // Sampling rate in Hz. Defines the rate at which waveform data is sampled during acquisition.
}

// MeasureIlluminationResponse generated response: slice of MeasurementResponseNumber
type MeasureIlluminationResponse []MeasurementResponseNumber

// MeasureIlluminationSpec pairs request and response types for script measure_illumination.json
type MeasureIlluminationSpec struct {
    Input MeasureIlluminationRequest `json:"input"`
    Output MeasureIlluminationResponse `json:"output"`
}

// MeasureLeakageRequest generated request (inputs) from schema measure_leakage.json
type MeasureLeakageRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to collect the applied voltage from
    Voltage float64 `json:"voltage"` // The voltage to apply to raise the gate voltage above ground in V.
}

// MeasureLeakageResponse generated response: single MeasurementResponseNumber
type MeasureLeakageResponse MeasurementResponseNumber

// MeasureLeakageSpec pairs request and response types for script measure_leakage.json
type MeasureLeakageSpec struct {
    Input MeasureLeakageRequest `json:"input"`
    Output MeasureLeakageResponse `json:"output"`
}

// RampRequest generated request (inputs) from schema ramp.json
type RampRequest struct {
    SetVoltages map[string]float64 `json:"setVoltages"` // Table mapping instrument target identifiers (as strings) to voltage values to set in V.
    Setters []InstrumentTarget `json:"setters"` // Instruments to write to.
}

// RampResponse generated response: no return (script omits returns)
type RampResponse struct {}

// RampSpec pairs request and response types for script ramp.json
type RampSpec struct {
    Input RampRequest `json:"input"`
    Output RampResponse `json:"output"`
}

// SetManyVoltagesRequest generated request (inputs) from schema set_many_voltages.json
type SetManyVoltagesRequest struct {
    SetVoltages map[string]float64 `json:"setVoltages"` // Table mapping instrument target identifiers (as strings) to voltage values to set in V.
    Setters []InstrumentTarget `json:"setters"` // Instruments to write to.
}

// SetManyVoltagesResponse generated response: no return (script omits returns)
type SetManyVoltagesResponse struct {}

// SetManyVoltagesSpec pairs request and response types for script set_many_voltages.json
type SetManyVoltagesSpec struct {
    Input SetManyVoltagesRequest `json:"input"`
    Output SetManyVoltagesResponse `json:"output"`
}

// SetNumberOfSamplesRequest generated request (inputs) from schema set_number_of_samples.json
type SetNumberOfSamplesRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to collect the number of samples from
    NumberOfSamples float64 `json:"numberOfSamples"` // The number of samples to set.
}

// SetNumberOfSamplesResponse generated response: no return (script omits returns)
type SetNumberOfSamplesResponse struct {}

// SetNumberOfSamplesSpec pairs request and response types for script set_number_of_samples.json
type SetNumberOfSamplesSpec struct {
    Input SetNumberOfSamplesRequest `json:"input"`
    Output SetNumberOfSamplesResponse `json:"output"`
}

// SetSampleRateRequest generated request (inputs) from schema set_sample_rate.json
type SetSampleRateRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to collect the sample rate from.
    SampleRate float64 `json:"sampleRate"` // The sample rate to set in units of samples/msec.
}

// SetSampleRateResponse generated response: no return (script omits returns)
type SetSampleRateResponse struct {}

// SetSampleRateSpec pairs request and response types for script set_sample_rate.json
type SetSampleRateSpec struct {
    Input SetSampleRateRequest `json:"input"`
    Output SetSampleRateResponse `json:"output"`
}

// SetSlopeRequest generated request (inputs) from schema set_slope.json
type SetSlopeRequest struct {
    Setter InstrumentTarget `json:"setter"` // The instrument (and channel) to apply the slope to. The slope is the DC ramp slope of the gate bias voltage.
    Slope float64 `json:"slope"` // The slope to apply in V/sec. Defines the rate at which waveform data is sloped when ramped.
}

// SetSlopeResponse generated response: no return (script omits returns)
type SetSlopeResponse struct {}

// SetSlopeSpec pairs request and response types for script set_slope.json
type SetSlopeSpec struct {
    Input SetSlopeRequest `json:"input"`
    Output SetSlopeResponse `json:"output"`
}

// SetTriggerLeaderRequest generated request (inputs) from schema set_trigger_leader.json
type SetTriggerLeaderRequest struct {
    Getter InstrumentTarget `json:"getter"` // The instrument (and channel) to set to be the leader. The leader is in charge of syncing with the ADC and triggering the rest of the measurements.
}

// SetTriggerLeaderResponse generated response: no return (script omits returns)
type SetTriggerLeaderResponse struct {}

// SetTriggerLeaderSpec pairs request and response types for script set_trigger_leader.json
type SetTriggerLeaderSpec struct {
    Input SetTriggerLeaderRequest `json:"input"`
    Output SetTriggerLeaderResponse `json:"output"`
}

// SetVoltageRequest generated request (inputs) from schema set_voltage.json
type SetVoltageRequest struct {
    SetVoltage float64 `json:"setVoltage"` // The voltage value to set in V
    Setter InstrumentTarget `json:"setter"` // The instrument (and channel) to set the applied voltage to
}

// SetVoltageResponse generated response: no return (script omits returns)
type SetVoltageResponse struct {}

// SetVoltageSpec pairs request and response types for script set_voltage.json
type SetVoltageSpec struct {
    Input SetVoltageRequest `json:"input"`
    Output SetVoltageResponse `json:"output"`
}

// Serialize converts InstrumentTarget to a string representation
func (t InstrumentTarget) Serialize() string {
    if t.Channel != 0 {
        return fmt.Sprintf("%s:%d", t.Id, t.Channel)
    }
    return t.Id
}
