// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: instserver/daemon/v1/daemon_messages.proto

package daemonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_DaemonStatus_FullMethodName      = "/instserver.daemon.v1.DaemonService/DaemonStatus"
	DaemonService_StartInstrument_FullMethodName   = "/instserver.daemon.v1.DaemonService/StartInstrument"
	DaemonService_StopInstrument_FullMethodName    = "/instserver.daemon.v1.DaemonService/StopInstrument"
	DaemonService_InstrumentStatus_FullMethodName  = "/instserver.daemon.v1.DaemonService/InstrumentStatus"
	DaemonService_ListInstruments_FullMethodName   = "/instserver.daemon.v1.DaemonService/ListInstruments"
	DaemonService_MeasureJob_FullMethodName        = "/instserver.daemon.v1.DaemonService/MeasureJob"
	DaemonService_JobStatus_FullMethodName         = "/instserver.daemon.v1.DaemonService/JobStatus"
	DaemonService_MeasureJobResult_FullMethodName  = "/instserver.daemon.v1.DaemonService/MeasureJobResult"
	DaemonService_JobList_FullMethodName           = "/instserver.daemon.v1.DaemonService/JobList"
	DaemonService_CancelJob_FullMethodName         = "/instserver.daemon.v1.DaemonService/CancelJob"
	DaemonService_Discover_FullMethodName          = "/instserver.daemon.v1.DaemonService/Discover"
	DaemonService_ListDataBuffers_FullMethodName   = "/instserver.daemon.v1.DaemonService/ListDataBuffers"
	DaemonService_ReleaseBuffer_FullMethodName     = "/instserver.daemon.v1.DaemonService/ReleaseBuffer"
	DaemonService_GetBufferMetadata_FullMethodName = "/instserver.daemon.v1.DaemonService/GetBufferMetadata"
	DaemonService_StopDaemon_FullMethodName        = "/instserver.daemon.v1.DaemonService/StopDaemon"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	DaemonStatus(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatusResponse, error)
	StartInstrument(ctx context.Context, in *StartInstrumentRequest, opts ...grpc.CallOption) (*StartInstrumentResponse, error)
	StopInstrument(ctx context.Context, in *StopInstrumentRequest, opts ...grpc.CallOption) (*StopInstrumentResponse, error)
	InstrumentStatus(ctx context.Context, in *InstrumentStatusRequest, opts ...grpc.CallOption) (*InstrumentStatusResponse, error)
	ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error)
	MeasureJob(ctx context.Context, in *MeasureJobRequest, opts ...grpc.CallOption) (*MeasureJobResponse, error)
	JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	MeasureJobResult(ctx context.Context, in *MeasureJobResultRequest, opts ...grpc.CallOption) (*MeasureJobResultResponse, error)
	JobList(ctx context.Context, in *JobListRequest, opts ...grpc.CallOption) (*JobListResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	ListDataBuffers(ctx context.Context, in *ListDataBuffersRequest, opts ...grpc.CallOption) (*ListDataBuffersResponse, error)
	ReleaseBuffer(ctx context.Context, in *ReleaseBufferRequest, opts ...grpc.CallOption) (*ReleaseBufferResponse, error)
	GetBufferMetadata(ctx context.Context, in *GetBufferMetadataRequest, opts ...grpc.CallOption) (*GetBufferMetadataResponse, error)
	StopDaemon(ctx context.Context, in *DaemonStop, opts ...grpc.CallOption) (*StandardResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) DaemonStatus(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_DaemonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartInstrument(ctx context.Context, in *StartInstrumentRequest, opts ...grpc.CallOption) (*StartInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInstrumentResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopInstrument(ctx context.Context, in *StopInstrumentRequest, opts ...grpc.CallOption) (*StopInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopInstrumentResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) InstrumentStatus(ctx context.Context, in *InstrumentStatusRequest, opts ...grpc.CallOption) (*InstrumentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstrumentStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_InstrumentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstrumentsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) MeasureJob(ctx context.Context, in *MeasureJobRequest, opts ...grpc.CallOption) (*MeasureJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeasureJobResponse)
	err := c.cc.Invoke(ctx, DaemonService_MeasureJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_JobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) MeasureJobResult(ctx context.Context, in *MeasureJobResultRequest, opts ...grpc.CallOption) (*MeasureJobResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeasureJobResultResponse)
	err := c.cc.Invoke(ctx, DaemonService_MeasureJobResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) JobList(ctx context.Context, in *JobListRequest, opts ...grpc.CallOption) (*JobListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, DaemonService_JobList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, DaemonService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, DaemonService_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListDataBuffers(ctx context.Context, in *ListDataBuffersRequest, opts ...grpc.CallOption) (*ListDataBuffersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataBuffersResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListDataBuffers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ReleaseBuffer(ctx context.Context, in *ReleaseBufferRequest, opts ...grpc.CallOption) (*ReleaseBufferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseBufferResponse)
	err := c.cc.Invoke(ctx, DaemonService_ReleaseBuffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetBufferMetadata(ctx context.Context, in *GetBufferMetadataRequest, opts ...grpc.CallOption) (*GetBufferMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBufferMetadataResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetBufferMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopDaemon(ctx context.Context, in *DaemonStop, opts ...grpc.CallOption) (*StandardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StandardResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	DaemonStatus(context.Context, *DaemonStatusRequest) (*DaemonStatusResponse, error)
	StartInstrument(context.Context, *StartInstrumentRequest) (*StartInstrumentResponse, error)
	StopInstrument(context.Context, *StopInstrumentRequest) (*StopInstrumentResponse, error)
	InstrumentStatus(context.Context, *InstrumentStatusRequest) (*InstrumentStatusResponse, error)
	ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error)
	MeasureJob(context.Context, *MeasureJobRequest) (*MeasureJobResponse, error)
	JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error)
	MeasureJobResult(context.Context, *MeasureJobResultRequest) (*MeasureJobResultResponse, error)
	JobList(context.Context, *JobListRequest) (*JobListResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	ListDataBuffers(context.Context, *ListDataBuffersRequest) (*ListDataBuffersResponse, error)
	ReleaseBuffer(context.Context, *ReleaseBufferRequest) (*ReleaseBufferResponse, error)
	GetBufferMetadata(context.Context, *GetBufferMetadataRequest) (*GetBufferMetadataResponse, error)
	StopDaemon(context.Context, *DaemonStop) (*StandardResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) DaemonStatus(context.Context, *DaemonStatusRequest) (*DaemonStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DaemonStatus not implemented")
}
func (UnimplementedDaemonServiceServer) StartInstrument(context.Context, *StartInstrumentRequest) (*StartInstrumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstrument not implemented")
}
func (UnimplementedDaemonServiceServer) StopInstrument(context.Context, *StopInstrumentRequest) (*StopInstrumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInstrument not implemented")
}
func (UnimplementedDaemonServiceServer) InstrumentStatus(context.Context, *InstrumentStatusRequest) (*InstrumentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstrumentStatus not implemented")
}
func (UnimplementedDaemonServiceServer) ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstruments not implemented")
}
func (UnimplementedDaemonServiceServer) MeasureJob(context.Context, *MeasureJobRequest) (*MeasureJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MeasureJob not implemented")
}
func (UnimplementedDaemonServiceServer) JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobStatus not implemented")
}
func (UnimplementedDaemonServiceServer) MeasureJobResult(context.Context, *MeasureJobResultRequest) (*MeasureJobResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MeasureJobResult not implemented")
}
func (UnimplementedDaemonServiceServer) JobList(context.Context, *JobListRequest) (*JobListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobList not implemented")
}
func (UnimplementedDaemonServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedDaemonServiceServer) Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedDaemonServiceServer) ListDataBuffers(context.Context, *ListDataBuffersRequest) (*ListDataBuffersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDataBuffers not implemented")
}
func (UnimplementedDaemonServiceServer) ReleaseBuffer(context.Context, *ReleaseBufferRequest) (*ReleaseBufferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseBuffer not implemented")
}
func (UnimplementedDaemonServiceServer) GetBufferMetadata(context.Context, *GetBufferMetadataRequest) (*GetBufferMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBufferMetadata not implemented")
}
func (UnimplementedDaemonServiceServer) StopDaemon(context.Context, *DaemonStop) (*StandardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopDaemon not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_DaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DaemonStatus(ctx, req.(*DaemonStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartInstrument(ctx, req.(*StartInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopInstrument(ctx, req.(*StopInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_InstrumentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstrumentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).InstrumentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_InstrumentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).InstrumentStatus(ctx, req.(*InstrumentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstrumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListInstruments(ctx, req.(*ListInstrumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_MeasureJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).MeasureJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_MeasureJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).MeasureJob(ctx, req.(*MeasureJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_JobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).JobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_JobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).JobStatus(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_MeasureJobResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureJobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).MeasureJobResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_MeasureJobResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).MeasureJobResult(ctx, req.(*MeasureJobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_JobList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).JobList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_JobList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).JobList(ctx, req.(*JobListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListDataBuffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataBuffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListDataBuffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListDataBuffers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListDataBuffers(ctx, req.(*ListDataBuffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ReleaseBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseBufferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ReleaseBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ReleaseBuffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ReleaseBuffer(ctx, req.(*ReleaseBufferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetBufferMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBufferMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetBufferMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetBufferMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetBufferMetadata(ctx, req.(*GetBufferMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonStop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopDaemon(ctx, req.(*DaemonStop))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "instserver.daemon.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DaemonStatus",
			Handler:    _DaemonService_DaemonStatus_Handler,
		},
		{
			MethodName: "StartInstrument",
			Handler:    _DaemonService_StartInstrument_Handler,
		},
		{
			MethodName: "StopInstrument",
			Handler:    _DaemonService_StopInstrument_Handler,
		},
		{
			MethodName: "InstrumentStatus",
			Handler:    _DaemonService_InstrumentStatus_Handler,
		},
		{
			MethodName: "ListInstruments",
			Handler:    _DaemonService_ListInstruments_Handler,
		},
		{
			MethodName: "MeasureJob",
			Handler:    _DaemonService_MeasureJob_Handler,
		},
		{
			MethodName: "JobStatus",
			Handler:    _DaemonService_JobStatus_Handler,
		},
		{
			MethodName: "MeasureJobResult",
			Handler:    _DaemonService_MeasureJobResult_Handler,
		},
		{
			MethodName: "JobList",
			Handler:    _DaemonService_JobList_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _DaemonService_CancelJob_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _DaemonService_Discover_Handler,
		},
		{
			MethodName: "ListDataBuffers",
			Handler:    _DaemonService_ListDataBuffers_Handler,
		},
		{
			MethodName: "ReleaseBuffer",
			Handler:    _DaemonService_ReleaseBuffer_Handler,
		},
		{
			MethodName: "GetBufferMetadata",
			Handler:    _DaemonService_GetBufferMetadata_Handler,
		},
		{
			MethodName: "StopDaemon",
			Handler:    _DaemonService_StopDaemon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "instserver/daemon/v1/daemon_messages.proto",
}
