BarrierGates: B1;B2;B3;B4;B5;B6
Ohmics: O1;O2;O3;O4
PlungerGates: P1;P2;P3;P4
ReservoirGates: R1;R2;R3;R4
ScreeningGates: S1;S2;S3
groups:
  group1:
    BarrierGates: B1;B2;B3:B4
    Name: I_O1
    NumDots: 3
    Order: O1;R1;B1;P1;B2;P2;B3;P3;B4;R2;O2
    PlungerGates: P1;P2;P3
    ReservoirGates: R1;R2
    ScreeningGates: S1;S2
  group2:
    BarrierGates: B5;B6
    Name: I_O3
    NumDots: 1
    Order: O3;R3;B5;P4;B6;R4;O4
    PlungerGates: P4
    ReservoirGates: R3;R4
    ScreeningGates: S2;S3
num-unique-channels: 2
wiringDC:
  B1:
    capacitance: 1.0e-12
    resistance: 1000.0
  B2:
    capacitance: 1.0e-12
    resistance: 1000.0
  B3:
    capacitance: 1.0e-12
    resistance: 1000.0
  B4:
    capacitance: 1.0e-12
    resistance: 1000.0
  B5:
    capacitance: 1.0e-12
    resistance: 1000.0
  B6:
    capacitance: 1.0e-12
    resistance: 1000.0
  O1:
    capacitance: 1.0e-12
    resistance: 1000.0
  O2:
    capacitance: 1.0e-12
    resistance: 1000.0
  O3:
    capacitance: 1.0e-12
    resistance: 1000.0
  O4:
    capacitance: 1.0e-12
    resistance: 1000.0
  P1:
    capacitance: 1.0e-12
    resistance: 1000.0
  P2:
    capacitance: 1.0e-12
    resistance: 1000.0
  P3:
    capacitance: 1.0e-12
    resistance: 1000.0
  P4:
    capacitance: 1.0e-12
    resistance: 1000.0
  R1:
    capacitance: 1.0e-12
    resistance: 1000.0
  R2:
    capacitance: 1.0e-12
    resistance: 1000.0
  R3:
    capacitance: 1.0e-12
    resistance: 1000.0
  R4:
    capacitance: 1.0e-12
    resistance: 1000.0
  S1:
    capacitance: 1.0e-12
    resistance: 1000.0
  S2:
    capacitance: 1.0e-12
    resistance: 1000.0
  S3:
    capacitance: 1.0e-12
    resistance: 1000.0
