package compiler

import (
	"fmt"
	"strings"
)

// MeasurementRequest represents a measurement request from the hub
type MeasurementRequest struct {
	// InstrumentName is the name of the instrument to measure with
	InstrumentName string
	// Command is the measurement command to execute
	Command string
	// Parameters are the parameters for the measurement
	Parameters map[string]interface{}
	// Globals are global variables to pass to the measurement script
	Globals map[string]interface{}
}

// MeasurementScript represents a compiled measurement script
type MeasurementScript struct {
	// ScriptContent is the Lua script content
	ScriptContent string
	// Globals are the global variables to pass to the script
	Globals map[string]interface{}
}

// Compiler compiles measurement requests into Lua scripts for instrument-script-server
type Compiler struct {
	// TODO: Integrate falcon-core Go bindings from:
	// https://github.com/falcon-autotuning/falcon-core-libs/tree/main/go/falcon-core
	// This will replace the Python-based compilation in /src/server_daemons
}

// NewCompiler creates a new measurement compiler
func NewCompiler() *Compiler {
	return &Compiler{}
}

// CompileMeasurement compiles a measurement request into a Lua script
// 
// This function currently generates a basic Lua script template.
// TODO: Integrate falcon-core Go bindings for full measurement compilation:
//   - Use falcon-core to parse and validate measurement parameters
//   - Generate optimized measurement sequences
//   - Handle sweep and quantum measurement patterns
//   - Support measurement script templates from falcon-core
func (c *Compiler) CompileMeasurement(req *MeasurementRequest) (*MeasurementScript, error) {
	if req.InstrumentName == "" {
		return nil, fmt.Errorf("instrument name is required")
	}
	if req.Command == "" {
		return nil, fmt.Errorf("command is required")
	}

	// Generate a basic Lua script that uses the new format with main() function
	// This is a simplified version - full implementation will use falcon-core
	script := generateLuaScript(req)

	return &MeasurementScript{
		ScriptContent: script,
		Globals:       req.Globals,
	}, nil
}

// generateLuaScript generates a Lua script from a measurement request
// This is a placeholder implementation that will be replaced with falcon-core integration
func generateLuaScript(req *MeasurementRequest) string {
	var sb strings.Builder
	
	sb.WriteString("-- Auto-generated measurement script\n")
	sb.WriteString("-- TODO: Generated by falcon-core Go bindings\n\n")
	
	sb.WriteString("function main(ctx)\n")
	sb.WriteString("    ctx:log(\"Starting measurement\")\n\n")
	
	// Build the command string
	commandStr := fmt.Sprintf("%s.%s", req.InstrumentName, req.Command)
	
	// Add parameters if present
	if len(req.Parameters) > 0 {
		sb.WriteString("    local params = {\n")
		for key, value := range req.Parameters {
			sb.WriteString(fmt.Sprintf("        %s = %v,\n", key, formatLuaValue(value)))
		}
		sb.WriteString("    }\n\n")
		sb.WriteString(fmt.Sprintf("    local response = ctx:call(\"%s\", params)\n", commandStr))
	} else {
		sb.WriteString(fmt.Sprintf("    local response = ctx:call(\"%s\")\n", commandStr))
	}
	
	sb.WriteString("    local result = response:value()\n")
	sb.WriteString("    ctx:log(\"Measurement complete\")\n\n")
	sb.WriteString("    return result\n")
	sb.WriteString("end\n")
	
	return sb.String()
}

// formatLuaValue formats a Go value for Lua script
func formatLuaValue(v interface{}) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("\"%s\"", val)
	case bool:
		if val {
			return "true"
		}
		return "false"
	case nil:
		return "nil"
	default:
		return fmt.Sprintf("%v", val)
	}
}

// SelectMeasurementScript selects the appropriate measurement script based on request
//
// TODO: This function needs to be implemented to:
//   1. Use falcon-core Go bindings to analyze the measurement request
//   2. Select or generate the appropriate measurement script template
//   3. Apply request parameters to the template
//   4. Return the script path or content for instrument-script-server
//
// The implementation should replace the Python-based script selection that was
// previously done in /src/server_daemons
func (c *Compiler) SelectMeasurementScript(req *MeasurementRequest) (string, error) {
	// Placeholder implementation
	// In production, this would:
	// - Query falcon-core for available measurement patterns
	// - Match the request to a measurement script template
	// - Customize the script based on instrument capabilities
	// - Cache compiled scripts for reuse
	
	return "", fmt.Errorf("measurement script selection not yet implemented - requires falcon-core integration")
}
